AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create ECS cluster

Parameters:
  Image:
    Type: String
    Description: URI of image you would like to use
    Default: '424416207406.dkr.ecr.us-east-2.amazonaws.com/ecr-repo:latest'
  
  RoleArn:
    Type: String
    Description: Arn of the execution role
    Default: 'arn:aws:iam::424416207406:role/ecsTaskExecutionRole'


Resources:

FGTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn: !Ref RoleArn
      Cpu: 256
      Memory: 512
      NetworkMode: "awsvpc"
      ContainerDefinitions:
        - Name: "mycontainerapp"
          Image: !Ref Image
          MemoryReservation: 256
          Memory: 512
          PortMappings:
            - ContainerPort: 8081
              Protocol: tcp

FGECSService:
    Type: AWS::ECS::Service
    Properties:
      LaunchType: FARGATE
      Cluster: ECS-Fargate-cluster
      DesiredCount: 2
      TaskDefinition: !Ref FGTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !GetAtt !ImportValue ECSFargateContainersSG.GroupId
          Subnets: [ !ImportValue PrivateSubnet1, !ImportValue PrivateSubnet2 ]
